/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package campus.communicator;

import com.mysql.jdbc.PreparedStatement;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author aryan_000
 */
public class Register extends javax.swing.JFrame {
Connection conn = null;
   ResultSet rs = null;
   PreparedStatement pst = null;
   Statement statement = null;
    /**
     * Creates new form Register
     * @throws java.net.UnknownHostException
     */
    public Register() throws UnknownHostException {
        initComponents();
         
        InetAddress IP=InetAddress.getLocalHost();
         
        jLabel6.setText(IP.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Campus Communicator : Register");

        jLabel1.setText("Username : ");

        jTextField1.setText(" ");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Password : ");

        jLabel3.setText("Confirm Password : ");

        jLabel4.setText("IP Address : ");

        jLabel5.setText("Email : ");

        jTextField5.setText(" ");

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(" Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText(" ");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(48, 48, 48)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(33, 33, 33)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextField1.setText("");
        jTextField5.setText("");
        jPasswordField1.setText("");
        jPasswordField2.setText("");
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
private boolean validate_username(String username) {
   try{           
       Class.forName("com.mysql.jdbc.Driver");  // MySQL database connection
       String url = "jdbc:mysql://localhost:3306/"; 
        String dbName = "javachat";
        String driver = "com.mysql.jdbc.Driver"; 
        String user = "root"; 
        String pass = ""; 
        try { 
            Class.forName(driver).newInstance(); 
              conn = DriverManager.getConnection(url+dbName,user,pass); 
             // if(conn!=null)System.out.println("COnnected to database");
           // conn.close(); 
        }
        catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException e) { 
}  
         pst = (PreparedStatement) conn.prepareStatement("Select username from chatdb where username=?");
       pst.setString(1, username);  
       System.out.println(pst);
       rs = pst.executeQuery();                        
       if(rs.next())            
           return true;    
       else
           return false;            
   }
   catch(ClassNotFoundException | SQLException e){
       return false;
   }       
}

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // TODO add your handling code here:
        
        String s1 = jTextField1.getText();
        char[] p1 = jPasswordField1.getPassword();
        char[] p2 = jPasswordField2.getPassword();
        String s2 = String.copyValueOf(p2);
        String s3 = String.copyValueOf(p1);
        String s4 = jLabel6.getText();
        String s5 = jTextField5.getText();
        
        if(s1.length()==0 || s2.length()==0||s3.length()==0 || s5.length()==0)
        {
            JOptionPane.showMessageDialog(null,"Field Cannot be blank");
        }
        //System.err.println(s2 + " and " + s3);
        else  if(!(s2.equals(s3)))
       {   
           JOptionPane.showMessageDialog(null,"Passwords do not match");
           jPasswordField1.setText("");
           jPasswordField2.setText("");
       }
       
        else  if(s2.length()<4)
       {
           JOptionPane.showMessageDialog(null, "Password should be greater than 4 characters");
            jPasswordField1.setText("");
           jPasswordField2.setText("");
       }
       else if(validate_username(s1.trim()))
       {
           JOptionPane.showMessageDialog(null,"Username already exist");
           jTextField1.setText("");
           
       }
       else 
       {
           try{           
      // Class.forName("com.mysql.jdbc.Driver");  // MySQL database connection
       String url = "jdbc:mysql://localhost:3306/"; 
        String dbName = "javachat";
        String driver = "com.mysql.jdbc.Driver"; 
        String user = "root"; 
        String pass = ""; 
        try { 
            /* Class.forName(driver).newInstance(); 
              conn = DriverManager.getConnection(url+dbName,user,pass); 
            // if(conn!=null)System.out.println("COnnected to database");
           // conn.close(); 
                statement = conn.createStatement();
            */
              String sqlnew = "Create Database javachat";
              statement.executeUpdate(sqlnew);
              String tablenew = "create table chatdb\n" +
                "( \n" +
                "userid int primary key,\n" +
                "username  varchar(255) NOT NULL,\n" +
                "pass varchar(255) NOT NULL,\n" +
                "ipaddr varchar(255) NOT NULL Unique,\n" +
                "email varchar(255) NOT NULL\n" +
                "\n" +
                ");"; 
             //  statement.execute(tablenew);
              JOptionPane.showMessageDialog(null,"Database created");
             // pst = (PreparedStatement) conn.prepareStatement("insert into chatdb(username,pass,ipaddr,email,onlinestatus) values(?,?,?,?,?)");
              //pst.setInt(1,3);
             /* pst.setString(1, s1.trim());
              pst.setString(2, s2);
              pst.setString(3, s4);
              pst.setString(4,s5.trim());
              pst.setInt(5, 0);
              System.out.println(pst);
               boolean check  = pst.execute();
              */
              int check  = 1;
              if(check==1) 
              {JOptionPane.showMessageDialog( null, "You have successfully created your user account");
              
              close();
              Login nextframe = new Login();
              nextframe.setVisible(true); 
                  //System.out.println("I am reaching");
              }
              if(check==0) JOptionPane.showMessageDialog( null, "User cannot be added at this point of time ");
              
        } 
        catch (SQLException sqlException)
        {
            if(sqlException.getErrorCode()==1007)
            {
                try {
                    pst = (PreparedStatement) conn.prepareStatement("insert into chatdb(username,pass,ipaddr,email,onlinestatus) values(?,?,?,?,?)");
                    //pst.setInt(1,3);
                    pst.setString(1, s1.trim());
                    pst.setString(2, s2);
                    pst.setString(3, s4);
                    pst.setString(4, s5.trim());
                    pst.setInt(5, 0);
                    System.out.println(pst);
                    boolean check = pst.execute();
                    
                    if (!check) {
                        JOptionPane.showMessageDialog(null, "You have successfully created your user account");
                        
                        close();
                        Login nextframe = new Login();
                        nextframe.setVisible(true);
                        //System.out.println("I am reaching");
                    }
                    if (check) {
                        JOptionPane.showMessageDialog(null, "User cannot be added at this point of time ");
                    }
                } catch (SQLException sQLException) {
                } catch (HeadlessException headlessException) {
                }
              
            } 
            
            else {
                JOptionPane.showMessageDialog(null,"Some Error Occured");
            }
        }       
       }
           catch(HeadlessException e) { }
       }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new Register().setVisible(true);
                } catch (UnknownHostException ex) {
                    Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

private void close()
{
WindowEvent winclosing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winclosing);
}


}
